function Hcv = estHcv(Data)
%ESTHCV Identifiy Heating Curve From Data.
%
% Hcv = estHcv(Data)
% Hcv [idModels.GeneralizedStaticModel]: Static Model for Heating Curve
% Data [SimulationOutput]:  Contains timeseries data necessary for identification.
%                           Will be generated by simulate()

%% Identify Heating Curve 
Tsup = Data.T_sup_flo.Data; 
N = length(Tsup);
Tout = Data.In.T_out.Data(1:N);
Hcv = idModels.GeneralizedStaticModel(1,1,'Fun','idModels.func.fun_hcv','Parameters',[2 22 1/1.3],...
        'InputName','Außentemperatur','OutputName','Vorlauftemperatur','Name','Heizkurve');
Hcv.identify(Tsup,Tout);
figure('color','w'); scatter(Tout,Tsup,12,'ko','filled','MarkerFaceAlpha',.1,'MarkerEdgeAlpha',.1); Hcv.showModel('-r','axes',gca); 

end

